name: CI

on: [push]

jobs:
  test-and-docs:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        julia-version: ['1.8']
        python-version: ['3.8']
        r-version: ['4.2.1']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      # actually it seems that without installing `libcurl4-openssl-dev`, there also exists a libcurl.so, but at `/lib/x86_64-linux-gnu/libcurl.so.4` instead of `/usr/lib/x86_64-linux-gnu/libcurl.so.4`
      # for consistency with previous setting and also recommended at https://github.com/r-lib/actions/tree/v2/setup-r-dependencies, continue to install `libcurl4-openssl-dev`
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
      - name: Install Dependencies for R
        run: |
          r = getOption("repos")
          r["CRAN"] = "https://cloud.r-project.org/"
          options(repos=r)
          install.packages("remotes")
          remotes::install_github("szcf-weiya/fda")
          install.packages("lsei")
          install.packages("splines")
        shell: sudo Rscript {0}

      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # see also: https://stackoverflow.com/questions/8795617/how-to-pip-install-a-package-with-min-and-max-version-range
      # https://pip.pypa.io/en/stable/cli/pip_install/#examples
      - name: Install Dependencies for Python
        run: |
          python -m pip install --upgrade pip
          pip3 install wheel
          pip3 install "torch>=1.9.0" --extra-index-url https://download.pytorch.org/whl/cpu
          pip3 install torchsort
          pip3 install "numpy>=1.20.2"
          pip3 install tqdm
      
      - uses: julia-actions/julia-runtest@v1
        env:
          LD_LIBRARY_PATH: /opt/R/${{ matrix.r-version }}/lib/R/lib
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
      - uses: julia-actions/julia-docdeploy@v1
        if: ${{ matrix.os == 'ubuntu-20.04' && matrix.julia-version == '1.8' && matrix.python-version == '3.8' }} # only run docs in one env
        env:
          LD_LIBRARY_PATH: /opt/R/${{ matrix.r-version }}/lib/R/lib
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
