name: CI

on: [push]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install R
        run: |
          sudo apt-get install lsb-release
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -c -s)-cran35/"
          sudo apt update
          sudo apt install r-base
          sudo apt install libcurl4-openssl-dev
          sudo apt-get install libmpfr-dev

      - name: Install Dependencies for R
        run: |
          install.packages("fda")
          install.packages("lsei")
          install.packages("Iso")
          install.packages("cobs")
          install.packages("splines")
          install.packages("monmlp")
        shell: sudo Rscript {0}

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Dependencies for Python
        run: |
          python -m pip install --upgrade pip
          pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
          pip3 install torchsort
          pip3 install numpy
          pip3 install tqdm

      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          # DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
          GKSwstype: "100" #https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@example-block
        run: julia --project=docs/ docs/make.jl